### ISSUE TITLE
General Framework

### ISSUE THREAD

**Issue by spencer4maddie** [Separius/awesome-sentence-embedding#17]
Hi Separius,
As you have described how the sentence embedding work, I have some questions about applying a model into the framework. For example, for doc2vec, what is the encoder to generate contextualized embeddings, and what is the pooling method for those embeddings to build the sentence embedding? Also, for CNN encoder, what output of the encoder can be viewed as the contextualized embeddings? If the framework does not apply for these models, may I ask why ? 
Thanks.

**Comment by Separius** [comment]
Hi,
well, doc2vec does not generate contextualized word embeddings and it can be seen as a static GPT, in a way; what I mean is that in d2v, for each document we add a new document embedding to the beginning of it(like the addition of `[CLS]` token in BERT and GPT)

For the CNN encoders, it depends. But most of the time, what people mean by the contextualized embeddings is the last layer representation of a predictive model(language model or cloze model like BERT). This is not always true, for example in ELMO, contextualized representation is obtained from all of the intermediate layers.

Hope it helps.

**Comment by spencer4maddie** [comment]
Thanks for your reply, it helps a lot.
