### ISSUE TITLE
Sentence embeddings for Arabic

### ISSUE THREAD

**Issue by kmario23** [Separius/awesome-sentence-embedding#18]
Hello @Separius ,
  We've leveraged [SIF](https://github.com/PrincetonML/SIF) and [AraVec](https://github.com/bakrianoo/aravec) for computing sentence embeddings for Arabic, which we termed it as [AraSIF](https://github.com/DFKI-Interactive-Machine-Learning/AraSIF). The paper is yet to appear in official ACL-2019 proceedings. However, please feel free to add it to this list. You can find the bibtex in [AraSIF](https://github.com/DFKI-Interactive-Machine-Learning/AraSIF) repo.

Thanks!

**Comment by Separius** [comment]
Hi @kmario23 ,
I'll add it as soon as it's indexed by the semantic scholar(I'll add it to the inbox for now)

edit: added to inbox via 18fff70

**Comment by kmario23** [comment]
Hi @Separius,
  The proceedings are available now. Please feel free to add the official ACL paper [Incremental Domain Adaptation for Neural Machine Translation in Low-Resource Settings](https://www.aclweb.org/anthology/papers/W/W19/W19-4601) and the code repository [AraSIF](https://github.com/DFKI-Interactive-Machine-Learning/AraSIF). Thank you!
