### ISSUE TITLE
Massively Multilingual Sentence Embeddings for Zero-Shot Cross-Lingual Transfer and Beyond code

### ISSUE THREAD

**Issue by iuria21** [Separius/awesome-sentence-embedding#6]
Where do you see that the code linked to this paper is indeed a implementation of the paper? I can't see anything of this in the LASER repo of facebookresearch.
Can you help me? I'm just searching that code.
Thanks for your great job!

**Comment by Separius** [comment]
Thanks for mentioning this.
Yeah, you are right, I made a mistake and thought they have released their models.

**Comment by iuria21** [comment]
It seems that they've already published it in: 
https://github.com/facebookresearch/LASER

**Comment by Separius** [comment]
Yes, thanks for pointing it out.
added via 2b9f4a23ebed082f22f47f7f6cb042e0198ce17f
